<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="PRG_1_PlcTask" Id="{974f2793-1abb-41d3-ab47-a860d1c380f6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_1_PlcTask
VAR
	
	
END_VAR

    ]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*Ethercat Diagnostics*)
//DIAGNOSTICS();

PRG_Motors_Test();

// Functionblock for PTP motion between different appertures
//PRG_Motion();

// Vacuum and differential pumping
PRG_GATT();
// Injector
PRG_INJ();

//PRG_VGP();


]]></ST>
    </Implementation>
    <LineIds Name="PRG_1_PlcTask">
      <LineId Id="71" Count="0" />
      <LineId Id="45" Count="1" />
      <LineId Id="58" Count="3" />
      <LineId Id="64" Count="3" />
      <LineId Id="2" Count="0" />
      <LineId Id="112" Count="0" />
      <LineId Id="111" Count="0" />
      <LineId Id="69" Count="1" />
      <LineId Id="68" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>